# Generated by Django 3.2.8 on 2022-01-06 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('Créateur', 'All'), ('Restreint', 'Restricted')], default='Restreint', max_length=250)),
                ('role', models.CharField(choices=[('Créateur', 'Creator'), ('Collaborateur', 'Collaborator')], default='Collaborateur', max_length=20)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'collaborateur',
                'verbose_name_plural': 'collaborateurs',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Back-end', 'Back End'), ('front-end', 'Front End'), ('IOS', 'Ios'), ('Android', 'Android')], max_length=15)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contributor', models.ManyToManyField(related_name='contributions', through='api.Contributors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.AddField(
            model_name='contributors',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects'),
        ),
        migrations.AlterUniqueTogether(
            name='contributors',
            unique_together={('contributor', 'project')},
        ),
    ]
