# Generated by Django 3.2.8 on 2022-01-21 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('Créateur', 'All'), ('Restreint', 'Restricted')], default='Restreint', max_length=250)),
                ('role', models.CharField(choices=[('Créateur', 'Creator'), ('Collaborateur', 'Collaborator')], default='Collaborateur', max_length=20)),
            ],
            options={
                'verbose_name': 'collaborateur',
                'verbose_name_plural': 'collaborateurs',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Back-end', 'Back End'), ('Front-end', 'Front End'), ('IOS', 'Ios'), ('Android', 'Android')], max_length=15)),
                ('contributor', models.ManyToManyField(related_name='contributions', through='api.Contributors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255)),
                ('tag', models.CharField(choices=[('bug', 'Incident'), ('tâche', 'Ticket'), ('amélioration', 'Change')], default='amélioration', max_length=20)),
                ('priority', models.CharField(choices=[('Faible', 'Low'), ('Moyenne', 'Medium'), ('Haute', 'High')], default='Faible', max_length=20)),
                ('status', models.CharField(choices=[('A faire', 'To Do'), ('En cours', 'In Progess'), ('Terminé', 'Finished')], default='A faire', max_length=20)),
                ('created_time', models.DateTimeField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
            ],
            options={
                'verbose_name': 'Problème',
                'verbose_name_plural': 'Problèmes',
            },
        ),
        migrations.AddField(
            model_name='contributors',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects'),
        ),
        migrations.AddField(
            model_name='contributors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.issues')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
            },
        ),
        migrations.AlterUniqueTogether(
            name='contributors',
            unique_together={('user', 'project')},
        ),
    ]
