# Generated by Django 3.2.8 on 2022-01-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
