# Generated by Django 3.2.8 on 2022-01-12 12:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_comments_issues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='contributor',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='contributors',
            unique_together={('user', 'project')},
        ),
    ]
