# Generated by Django 3.2.8 on 2022-01-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220112_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='contributor',
            new_name='user',
        ),
    ]
