# Generated by Django 3.2.8 on 2022-01-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_contributor_projects_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='user',
            new_name='contributor',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='author',
        ),
    ]
